# config.py — Week 1: Constants Scaffold
SCREEN_WIDTH  = 1280
SCREEN_HEIGHT = 720
FPS           = 60

PLAY_WIDTH    = 800
PLAY_HEIGHT   = 400

BALL_RADIUS   = 15
POCKET_RADIUS = 20

# Colors
WHITE  = (255, 255, 255)
BLACK  = (0,   0,   0)
GREEN  = (0,   128, 0)
RED    = (220, 50,  50)
YELLOW = (240, 200, 0)
BLUE   = (50,  100, 220)
BROWN  = (101, 67,  33)

# Application States
STATE_MENU         = "MENU"
STATE_INPUT_NAMES  = "INPUT_NAMES"
STATE_PLAYING      = "PLAYING"
STATE_PAUSED       = "PAUSED"
STATE_GAME_OVER    = "GAME_OVER"
STATE_TUTORIAL     = "TUTORIAL"
STATE_SETTINGS     = "SETTINGS"
STATE_LEADERBOARD  = "LEADERBOARD"
STATE_TEAM         = "TEAM"